<div id="clock-wrapper" class="flex justify-center items-center mb-6">
    <div id="clock-container" class="clock-container relative select-none cursor-pointer"
         style="width: min(520px, 90vw); height: min(520px, 90vw);">
        <!-- Analog SVG clock -->
        <svg id="analog-clock" viewBox="0 0 200 200" class="w-full h-full rounded-full"
             role="img" aria-label="Analog clock">
            <defs>
                <radialGradient id="g" cx="50%" cy="40%">
                    <stop offset="0%" stop-color="#ffffff"/>
                    <stop offset="100%" stop-color="#f3f4f6"/>
                </radialGradient>
            </defs>

            <!-- outer ring -->
            <circle cx="100" cy="100" r="98" fill="url(#g)" stroke="#e5e7eb" stroke-width="2"/>

            <!-- ticks -->
            <g id="ticks" stroke="#9ca3af" stroke-linecap="round">
                <!-- minute ticks (generated by JS for clarity) -->
            </g>

            <!-- hour numbers -->
            <g id="numbers" fill="#374151" font-size="10" font-family="system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial">
                <!-- numbers drawn by JS -->
            </g>

            <!-- hands -->
            <g id="hands" transform="translate(100,100)">
                <line id="hour-hand" x1="0" y1="0" x2="0" y2="-45" stroke="#111827" stroke-width="5" stroke-linecap="round" />
                <line id="minute-hand" x1="0" y1="0" x2="0" y2="-65" stroke="#111827" stroke-width="3.5" stroke-linecap="round" />
                <line id="second-hand" x1="0" y1="8" x2="0" y2="-75" stroke="#ef4444" stroke-width="1.5" stroke-linecap="round" />
                <circle cx="0" cy="0" r="3.5" fill="#111827" />
            </g>

            <!-- digital overlay (hidden by default) -->
            <foreignObject id="digital-fo" x="30" y="76" width="140" height="48" style="display:none">
                <div xmlns="http://www.w3.org/1999/xhtml" class="w-full h-full flex items-center justify-center">
                    <div id="digital-display" style="font-family:system-ui, -apple-system, 'Segoe UI', Roboto; font-size:18px; color:#111827;"></div>
                </div>
            </foreignObject>
        </svg>
    </div>
</div>
